title:        "eardil"
tagline:      'eardil's Journey'
description:  'journey into scientific computing'
url:          eardil.github.io
version:      1.1.1
author:
  name:       'Irving SW'
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
