title:        "Eärdil's"
tagline:      "Eardil's Journey"
description:  'journey around the modern scientific computing workflow.'
url:          eardil.github.io
version:      1.1.1
author:
  name:       'Irving SW'
  email:      ''
markdown:     kramdown
mathjax:      true
permalink:    pretty
pygments:     true
paginate:     5
