title:        "Eärdil's"
tagline:      "Eardil's Journey"
description:  'journey around the modern scientific computing workflow.'
url:          eardil.github.io
version:      1.1.1
author:
  name:       'Irving SW'
  email:      ''
markdown:     kramdown
mathjax:      true
permalink:    pretty
pygments:     true
paginate:     5
encoding: 	  UTF-8


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
